[pytest]
# Directory containing tests
testpaths = tests
# Allure: save reults to this directory to generate report
addopts =
    --alluredir=allure-results
    --clean-alluredir
    --v
    --tb=short
# Register custom markers to avoid warnings
markers =
    smoke: Quick sanity tests
    regression: Full regression suite
    auth: Tests related to authentication
    book: Tests related to book management
    category: Tests related to category management
# Log format displayed in terminal
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_date_format = %Y-%m-%s %H:%M:%S